config/routes.rb
KasetBay::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activation_token/:token" => "users#activate", :as => "activation"
  get "recovery_token/:token" => "users#reset_password", :as => "reset_password"
  get "admin" => "admin#index", :as => "admin"
  get "tos" => "main#tos", :as => "tos"

  resources :sessions, :only => [:create]

  resources :users, :except => [:show] do
    collection do
      get :activate
      get :forget_password
      post :generate_recovery_token
    end

    member do
      get :resend_activation_email
    end
  end

  resources :sites, :except => [:new, :create] do
    member do
      get :dashboard
    end

    scope module: :sites do
      resource :publishing, :only => [:edit, :update]
    end

    resource :contact_info, :only => [:edit, :update]
    resources :menus, :except => [:show] do
      collection do
        post :sort
      end
      member do
        put :toggle_enabled
      end
    end

    resources :categories

    resources :pages, except: [:show] do
      collection do
        post :sort
      end

      resources :pictures, :only => [:index] do
        collection do
          put :create
        end
      end
    end
    resources :pictures, :only => [:destroy]
  end

  resources :categories, only: [], :path => "" do
    resources :pages, only: [:show], :path => ""
  end
  resources :pages, only: [:show], :path => ""

  constraints(Subdomain) do
    match "/" => "sites#show"
  end

  root :to => 'main#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :subdomain, :title, :sub_title, :meta_description, :meta_keywords,
                  :sidebar_color, :article_color, :footer_color,
                  :logo, :header_image, :background_image

  has_one :contact_info, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :pages, dependent: :destroy
  has_many :pictures, dependent: :destroy
  belongs_to :user

  LOGO_STYLES = { normal: "x200" }
  has_attached_file :logo, styles: LOGO_STYLES, default_style: :normal,
                    default_url: "/assets/default/logo.png"

  HEADER_IMAGE_STYLES = { normal: "960x250#" }
  has_attached_file :header_image, styles: HEADER_IMAGE_STYLES, default_style: :normal,
                    default_url: "/assets/default/header.jpg"

  BACKGROUND_IMAGE_STYLES = { normal: "1280x800#" }
  has_attached_file :background_image, styles: BACKGROUND_IMAGE_STYLES, default_style: :normal,
                    default_url: "/assets/default/background.jpg"

  before_validation :prepare_site

  validates :subdomain, presence: true, format: { with: /^(?!^www$)[a-z0-9]+$/i },
                        length: { minimum: 3 }, uniqueness: true
  validates :sidebar_color, presence: true, format: { with: /#(\d|[abcdefABCDEF]){6}/ }
  validates :article_color, presence: true, format: { with: /#(\d|[abcdefABCDEF]){6}/ }
  validates :footer_color, presence: true, format: { with: /#(\d|[abcdefABCDEF]){6}/ }
  validates_attachment :logo,
                       content_type: { content_type: ACCEPTED_IMAGE_TYPES, message: I18n.translate('shared.error_messages.file_type') },
                       size: { less_than: 10.megabytes, message: I18n.translate('shared.error_messages.file_size') }
  validates_attachment :header_image,
                       content_type: { content_type: ACCEPTED_IMAGE_TYPES, message: I18n.translate('shared.error_messages.file_type') },
                       size: { less_than: 10.megabytes, message: I18n.translate('shared.error_messages.file_size') }
  validates_attachment :background_image,
                       content_type: { content_type: ACCEPTED_IMAGE_TYPES },
                       size: { less_than: 10.megabytes, message: I18n.translate('shared.error_messages.file_size') }

  scope :ordered, -> { order(:id) }

  def owner
    user
  end

  def url
    "http://" + subdomain + "." + DOMAIN_HOST
  end

  def toggle_published
    self.toggle! :published
  end

  def at_least_one_enabled_menu?
    menus.enabled.any?
  end

  def can_published?
    user.activated? &&
    contact_info.present? &&
    at_least_one_enabled_menu?
  end

  private

  def prepare_site
    self.subdomain = self.subdomain.downcase
  end

end

app/controllers/sites/publishings_controller.rb
module Sites
  class PublishingsController < ApplicationController
    before_filter :get_site
    before_filter :owner_or_admin_required

    def edit
    end

    def update
      if (@site.published? || @site.can_published?) && @site.toggle_published
        flash.notice = t('sites.publishings.update.success')
      else
        flash.alert = t('sites.publishings.update.failure')
      end

      redirect_to edit_site_publishing_path(@site)
    end

  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :get_site, except: [:index]
  before_filter :owner_or_admin_required, except: [:index]
  before_filter :published_or_authenticated?, only: [:show]

  layout :resolve_layout

  def index
  end

  def show
    @site = Site.find_by_subdomain! request.subdomain
    @menus = @site.menus.enabled.ordered

    if @menus.any?
      @page = @menus.first.is_category? ? @menus.first.menuable.pages.first : @menus.first.menuable
      @pictures = @page.pictures
      render template: "pages/show"
    end
  end

  def edit
  end

  def update
    if @site.update_attributes params[:site]
      flash.now.notice= t('sites.update.success')
    else
      flash.now.alert = t('sites.update.failure')
    end

    render "edit"
  end

  def destroy
    @site.update_column :deleted, true
    raise "destroy"
  end

  def dashboard
  end

  private

  def get_site
    case action_name
    when "show"
      @site = Site.find_by_subdomain! request.subdomain
    else
      @site = Site.find_by_id params[:id]
    end
  end

end

app/views/sites/publishings/_step.html.haml
.step
  .row
    .col-md-9
      .b= t("sites.publishings.edit.step#{no}.title")
      .s= t("sites.publishings.edit.step#{no}.hint")
    .col-md-3.tar
      = publishing_checklist(status, path)

app/views/sites/publishings/edit.html.haml
.row
  .col-md-8.col-md-offset-2
    .container
      #publishing_checklists
        %h2= page_title t('sites.publishings.edit.title')
        = t('sites.publishings.edit.subtitle')

        = render "sites/publishings/step", no: 1, status: current_user.activated?, path: resend_activation_email_user_path(current_user)
        = render "sites/publishings/step", no: 2, status: @site.contact_info.present?, path: edit_site_contact_info_path(@site)
        = render "sites/publishings/step", no: 3, status: @site.at_least_one_enabled_menu?, path: site_menus_path(@site)

      #website_status.mtd
        .row
          .col-md-4.mtd.tac.vl
            .b= t('sites.publishings.edit.status')
          .col-md-4.mbh.tac
            - if @site.published?
              = link_to website_unpublished(@site.published?), site_publishing_path(@site), method: :put
            - else
              = website_unpublished(@site.published?)
            = t('sites.publishings.edit.unpublished_hint').html_safe
          .col-md-4.tac
            - unless @site.published?
              = link_to website_published(@site.published?), site_publishing_path(@site), method: :put
            - else
              = website_published(@site.published?)
            = t('sites.publishings.edit.published_hint')