config/routes.rb
KasetBay::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activation_token/:token" => "users#activate", :as => "activation"
  get "recovery_token/:token" => "users#reset_password", :as => "reset_password"
  get "admin" => "admin#index", :as => "admin"
  get "tos" => "main#tos", :as => "tos"

  resources :sessions, :only => [:create]

  resources :users, :except => [:show] do
    collection do
      get :activate
      get :forget_password
      post :generate_recovery_token
    end

    member do
      get :resend_activation_email
    end
  end

  resources :sites, :except => [:new, :create] do
    member do
      get :dashboard
    end

    scope module: :sites do
      resource :publishing, :only => [:edit, :update]
    end

    resource :contact_info, :only => [:edit, :update]
    resources :menus, :except => [:show] do
      collection do
        post :sort
      end
      member do
        put :toggle_enabled
      end
    end

    resources :categories

    resources :pages, except: [:show] do
      collection do
        post :sort
      end

      resources :pictures, :only => [:index] do
        collection do
          put :create
        end
      end
    end
    resources :pictures, :only => [:destroy]
  end

  resources :categories, only: [], :path => "" do
    resources :pages, only: [:show], :path => ""
  end
  resources :pages, only: [:show], :path => ""

  constraints(Subdomain) do
    match "/" => "sites#show"
  end

  root :to => 'main#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password

  has_many :sites, dependent: :destroy

  before_validation :prepare_user

  validates :email, presence: true, format: { with: /[\w+\-.]+@[a-z\d\-.]+\.[a-z]+/i },
                    uniqueness: true
  validates :password, length: { within: 6..40 }

  scope :active, -> { where(active: true) }
  scope :ordered, -> { order(:id) }

  def to_s
    email
  end

  def site
    sites.first if sites.any?
  end

  def activated?
    activation_token.nil?
  end

  def self.authenticate(email, password)
    sleep 1
    if (user = find_by_email(email)) && user.active && user.authenticate(password)
      user
    end
  end

  private

  def prepare_user
    self.email = self.email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :get_site, only: [:edit, :update]
  before_filter :owner_or_admin_required, only: [:edit, :update]
  before_filter :redirect_to_dashboard_if_authenticated, only: [:new, :create]
  skip_before_filter :authentication_required, except: [:index, :edit, :update, :destroy]

  def index
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new params[:site]

    @user.sign_up_ip = request.env["REMOTE_ADDR"]
    @user.activation_token = SecureRandom.hex
    @site.user = @user

    valid_user, valid_site = @user.valid?, @site.valid?

    if valid_user && valid_site && @user.save && @site.save
      DummyContent.new(@site).build_dummy_content
      log_in! @user
      SystemMailer.new_sign_up(@user).deliver
      redirect_to root_url, notice: t('users.create.success')
    else
      flash.now.alert = t('users.create.failure')
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes params[:user]
      flash.now.notice= t('users.update.success')
    else
      flash.now.alert = t('users.update.failure')
    end

    render "edit"
  end

  def destroy
    @user.update_column :deleted, true
    raise "destroy"
  end

  def activate
    if @user = User.find_by_activation_token(params[:token])
      @user.update_column :activation_token, nil
      log_in! @user
      redirect_to root_url, notice: t('users.activate.success')
    else
      redirect_to root_url, alert: t('users.activate.failure')
    end
  end

  def resend_activation_email
    SystemMailer.new_sign_up(current_user).deliver
    flash.notice = t('users.resend_activation_email')
    redirect_to request.referrer.gsub(/[?].*/, "")
  end

  def forget_password
  end

  def generate_recovery_token
    if params[:email] && user = User.find_by_email(params[:email].strip)
      user.update_column :recovery_token, SecureRandom.hex

      SystemMailer.reset_password(user).deliver
      flash.now.notice = t('users.generate_recovery_token.success')
    else
      flash.now.alert = t('users.generate_recovery_token.failure')
    end

    render "forget_password"
  end

  def reset_password
    if user = User.find_by_recovery_token(params[:token])
      user.update_column :recovery_token, nil
      log_in! user
      redirect_to edit_user_path(user), notice: t('users.reset_password.success')
    else
      redirect_to root_url, alert: t('users.reset_password.failure')
    end
  end

  private

  def get_site
    @site = @user.site
  end

  def get_user
    case action_name
    when "new"
      @user = User.new
    when "create"
      @user = User.new params[:user]
    when "edit", "update", "destroy"
      @user = User.find_by_id params[:id]
    end
  end

end

app/views/users/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    .container
      %h2= page_title t('users.edit.title')
      = render "shared/errors", object: @user

      = form_for @user do |f|
        .pyh
          = f.label :email
          = f.text_field :email, disabled: true, class: "form-control"
        .pyh.rel
          = f.label :password
          = f.password_field :password, class: "form-control"
          .abs{style: "top: 33px; right: 5px;"}
            = content_tag :a, id: "toggle_password", title: t('users.new.password_hint') do
              .ph.px.glyphicon.glyphicon-eye-close

        .pyh
          = f.submit t('shared.save'), class: "btn btn-block SPColorButton SPBlueColorButton"

app/views/users/forget_password.html.haml
.row
  .col-md-6.col-md-offset-3
    .container
      = render "shared/logo"

      %h2= page_title t('users.forget_password.title')
      .mbd= t('users.forget_password.subtitle')
      = form_tag generate_recovery_token_users_path do
        .pyh
          = label_tag :email, User.human_attribute_name(:email)
          = text_field_tag :email, params[:email], class: "form-control"
        .pyh
          = submit_tag t('users.forget_password.save'), class: "btn btn-block SPColorButton SPBlueColorButton"

app/views/users/new.html.haml
.row
  .col-md-6.col-md-offset-3
    .container
      = render "shared/logo"

      %h2= page_title t('users.new.title')
      = render "shared/errors", object: @user
      = render "shared/errors", object: @site

      = form_for @user do |f|
        .pyh
          = f.label :email
          = f.text_field :email, autofocus: (@user.errors.blank? && @site.errors.blank?), class: "form-control"
        .pyh.rel
          = f.label :password
          = f.password_field :password, class: "form-control"
          .abs{style: "top: 33px; right: 3px;"}
            = content_tag :a, id: "toggle_password", title: t('users.new.password_hint') do
              .ph.px.glyphicon.glyphicon-eye-close

        = fields_for @site do |s|
          .pyh.rel
            = s.label_with_hint :subdomain
            .input-group
              = s.text_field :subdomain, class: "form-control"
              %span.b.l.input-group-addon
                = ".#{DOMAIN_HOST}"

        .pyh
          = f.submit t('users.new.save'), class: "btn btn-block SPColorButton SPBlueColorButton"
      .fr
        = t('shared.or')
        = link_to t('sessions.new.link'), log_in_path
      %br
      .fr
        = t('shared.or')
        = link_to t('main.index.showcase.link2', website_name: WEBSITE_NAME), root_path(anchor: "showcase"), target: "_blank"

= render "shared/facebook_code"
= render "shared/adwords_sign_up_code"