config/routes.rb
KasetBay::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activation_token/:token" => "users#activate", :as => "activation"
  get "recovery_token/:token" => "users#reset_password", :as => "reset_password"
  get "admin" => "admin#index", :as => "admin"
  get "tos" => "main#tos", :as => "tos"

  resources :sessions, :only => [:create]

  resources :users, :except => [:show] do
    collection do
      get :activate
      get :forget_password
      post :generate_recovery_token
    end

    member do
      get :resend_activation_email
    end
  end

  resources :sites, :except => [:new, :create] do
    member do
      get :dashboard
    end

    scope module: :sites do
      resource :publishing, :only => [:edit, :update]
    end

    resource :contact_info, :only => [:edit, :update]
    resources :menus, :except => [:show] do
      collection do
        post :sort
      end
      member do
        put :toggle_enabled
      end
    end

    resources :categories

    resources :pages, except: [:show] do
      collection do
        post :sort
      end

      resources :pictures, :only => [:index] do
        collection do
          put :create
        end
      end
    end
    resources :pictures, :only => [:destroy]
  end

  resources :categories, only: [], :path => "" do
    resources :pages, only: [:show], :path => ""
  end
  resources :pages, only: [:show], :path => ""

  constraints(Subdomain) do
    match "/" => "sites#show"
  end

  root :to => 'main#index'

end

app/views/shared/_adwords_dashboard_code.html.erb
<!-- Google Code for Dashboard page Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 991520724;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "Bjd8CJT08wkQ1M_l2AM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/991520724/?label=Bjd8CJT08wkQ1M_l2AM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

app/views/shared/_adwords_sign_up_code.html.erb
<!-- Google Code for Sign up page Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 991520724;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "T2h3CKzx8wkQ1M_l2AM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/991520724/?label=T2h3CKzx8wkQ1M_l2AM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= property_id %>', 'kasetbay.com');
  ga('send', 'pageview');

</script>

app/views/shared/_empty.html.haml
%tr
  - colspan.times do
    %td .....

app/views/shared/_errors.html.haml
- if object.errors.present?
  %ul.errors
    - object.errors.full_messages.sort.each do |m|
      - unless m.match(/file size|content type/)
        %li= m.gsub(/\[|\]|"/, "")

app/views/shared/_facebook_code.html.erb
<!-- Facebook Conversion Code for f_sign_up_page -->
<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6017825253989';
fb_param.value = '0.00';
fb_param.currency = 'THB';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6017825253989&amp;value=0&amp;currency=THB" /></noscript>

app/views/shared/_facebook_like.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/th_TH/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div style="border: 2px solid #fff;" class="fb-page" data-href="https://www.facebook.com/kasetbay" data-hide-cover="false" data-show-facepile="false" data-show-posts="false">
  <div class="fb-xfbml-parse-ignore">
    <blockquote cite="https://www.facebook.com/kasetbay">
      <a href="https://www.facebook.com/kasetbay">Kaset Bay - ฟรีเวบไซต์สำหรับ สวน/ไร่/นา หรือธุรกิจการเกษตร</a>
    </blockquote>
  </div>
</div>

app/views/shared/_logo.html.haml
.pyd.tac
  = link_to root_path do
    = max_width_image_tag "/assets/logo.png", 100

app/views/shared/_top_menu.html.haml
.top_menu.pt
  .container
    .navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          = content_tag :button, type: "button", data: { toggle: "collapse", target: ".navbar-collapse" }, class: "navbar-toggle" do
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to t('shared.site_name'), root_path, class: "navbar-brand b"
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
              = link_to t('shared.top_menu.dashboard'), root_path
            %li.dropdown
              = content_tag :a, href: "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do
                = t('shared.top_menu.settings')
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to t('shared.top_menu.website_settings'), edit_site_path(@site)
                %li
                  = link_to t('shared.top_menu.contact_settings'), edit_site_contact_info_path(@site)
            %li.dropdown
              = content_tag :a, href: "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do
                = t('shared.top_menu.content')
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to t('shared.top_menu.pages'), site_pages_path(@site)
                %li
                  = link_to t('shared.top_menu.categories'), site_categories_path(@site)
                %li
                  = link_to t('shared.top_menu.menus'), site_menus_path(@site)
            %li
              = link_to t('shared.top_menu.publish'), edit_site_publishing_path(@site)
            - if admin?
              %li
                = link_to t('shared.top_menu.admin'), admin_path
          .log_out
            = link_to current_user, edit_user_path(current_user)
            %span.ml
              = link_to t('users.shared.log_out'), log_out_path, class: "SPColorButton SPRedColorButton"