config/routes.rb
KasetBay::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activation_token/:token" => "users#activate", :as => "activation"
  get "recovery_token/:token" => "users#reset_password", :as => "reset_password"
  get "admin" => "admin#index", :as => "admin"
  get "tos" => "main#tos", :as => "tos"

  resources :sessions, :only => [:create]

  resources :users, :except => [:show] do
    collection do
      get :activate
      get :forget_password
      post :generate_recovery_token
    end

    member do
      get :resend_activation_email
    end
  end

  resources :sites, :except => [:new, :create] do
    member do
      get :dashboard
    end

    scope module: :sites do
      resource :publishing, :only => [:edit, :update]
    end

    resource :contact_info, :only => [:edit, :update]
    resources :menus, :except => [:show] do
      collection do
        post :sort
      end
      member do
        put :toggle_enabled
      end
    end

    resources :categories

    resources :pages, except: [:show] do
      collection do
        post :sort
      end

      resources :pictures, :only => [:index] do
        collection do
          put :create
        end
      end
    end
    resources :pictures, :only => [:destroy]
  end

  resources :categories, only: [], :path => "" do
    resources :pages, only: [:show], :path => ""
  end
  resources :pages, only: [:show], :path => ""

  constraints(Subdomain) do
    match "/" => "sites#show"
  end

  root :to => 'main#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :background_image

  has_many :pages
  has_many :menus, as: :menuable
  belongs_to :site

  BACKGROUND_IMAGE_STYLES = { normal: "1280x800#" }
  has_attached_file :background_image, styles: BACKGROUND_IMAGE_STYLES, default_style: :normal,
                    default_url: "/assets/default/background.jpg"

  validates :title, presence: true, length: { maximum: 255 }
  validates_attachment :background_image,
                       content_type: { content_type: ACCEPTED_IMAGE_TYPES, message: I18n.translate('shared.error_messages.file_type') },
                       size: { less_than: 10.megabytes, message: I18n.translate('shared.error_messages.file_size') }

  default_scope where(deleted: false)
  scope :active, where(deleted: false)
  scope :not_empty, joins(:pages).where("pages.id IS NOT NULL AND pages.deleted = 'f'").uniq
  scope :ordered, order("title asc")

  def to_param
    "#{id}-#{slug}"
  end

  def slug
    title.downcase.gsub(" ", "-").gsub(".", "").gsub("/", "").gsub("%", "")
  end

  def reassign_pages(*page_ids)
    self.pages.delete_all

    page_ids.each do |page_id|
      if page = Page.find_by_id(page_id)
        self.pages << page
      end
    end

    clear_associations if pages.empty?
  end

  def destroy
    self.update_column :deleted, true
    clear_associations
  end

  private

  def clear_associations
    self.menus.each do |menu|
      menu.update_column :menuable_id, nil
      menu.update_column :menuable_type, nil
    end
  end

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :subdomain, :title, :sub_title, :meta_description, :meta_keywords,
                  :sidebar_color, :article_color, :footer_color,
                  :logo, :header_image, :background_image

  has_one :contact_info, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :pages, dependent: :destroy
  has_many :pictures, dependent: :destroy
  belongs_to :user

  LOGO_STYLES = { normal: "x200" }
  has_attached_file :logo, styles: LOGO_STYLES, default_style: :normal,
                    default_url: "/assets/default/logo.png"

  HEADER_IMAGE_STYLES = { normal: "960x250#" }
  has_attached_file :header_image, styles: HEADER_IMAGE_STYLES, default_style: :normal,
                    default_url: "/assets/default/header.jpg"

  BACKGROUND_IMAGE_STYLES = { normal: "1280x800#" }
  has_attached_file :background_image, styles: BACKGROUND_IMAGE_STYLES, default_style: :normal,
                    default_url: "/assets/default/background.jpg"

  before_validation :prepare_site

  validates :subdomain, presence: true, format: { with: /^(?!^www$)[a-z0-9]+$/i },
                        length: { minimum: 3 }, uniqueness: true
  validates :sidebar_color, presence: true, format: { with: /#(\d|[abcdefABCDEF]){6}/ }
  validates :article_color, presence: true, format: { with: /#(\d|[abcdefABCDEF]){6}/ }
  validates :footer_color, presence: true, format: { with: /#(\d|[abcdefABCDEF]){6}/ }
  validates_attachment :logo,
                       content_type: { content_type: ACCEPTED_IMAGE_TYPES, message: I18n.translate('shared.error_messages.file_type') },
                       size: { less_than: 10.megabytes, message: I18n.translate('shared.error_messages.file_size') }
  validates_attachment :header_image,
                       content_type: { content_type: ACCEPTED_IMAGE_TYPES, message: I18n.translate('shared.error_messages.file_type') },
                       size: { less_than: 10.megabytes, message: I18n.translate('shared.error_messages.file_size') }
  validates_attachment :background_image,
                       content_type: { content_type: ACCEPTED_IMAGE_TYPES },
                       size: { less_than: 10.megabytes, message: I18n.translate('shared.error_messages.file_size') }

  scope :ordered, -> { order(:id) }

  def owner
    user
  end

  def url
    "http://" + subdomain + "." + DOMAIN_HOST
  end

  def toggle_published
    self.toggle! :published
  end

  def at_least_one_enabled_menu?
    menus.enabled.any?
  end

  def can_published?
    user.activated? &&
    contact_info.present? &&
    at_least_one_enabled_menu?
  end

  private

  def prepare_site
    self.subdomain = self.subdomain.downcase
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :get_site
  before_filter :owner_or_admin_required
  before_filter :get_category, except: [:index]
  before_filter :get_all_pages, except: [:index, :destroy]
  before_filter :category_limit, only: [:new, :create]

  def index
    @categories = @site.categories.active.ordered
  end

  def new
  end

  def create
    @category.site = @site
    if @category.update_attributes params[:category]
      @category.reassign_pages *params[:page_ids]

      flash.notice= t('categories.create.success')
      redirect_to action: "index"
    else
      flash.now.alert = t('categories.create.failure')
      render "new"
    end
  end

  def edit
  end

  def update
    if @category.update_attributes params[:category]
      @category.reassign_pages *params[:page_ids]

      flash.notice= t('categories.update.success')
      redirect_to action: "index"
    else
      flash.now.alert = t('categories.update.failure')
      render "edit"
    end
  end

  def destroy
    @category.destroy
    flash.notice = t('categories.destroy.success', name: @category.title)

    redirect_to action: "index"
  end

  private

  def get_category
    case action_name
    when "new", "create"
      @category = Category.new
    else
      @category = Category.find_by_id params[:id]
    end
  end

  def get_all_pages
    @all_pages = @site.pages.ordered
  end

  def category_limit
    if !admin? && @site.categories.count >= CATEGORY_LIMIT
      flash.alert = t('categories.shared.limitation')
      redirect_to site_categories_path(@site)
    end
  end

end

app/views/categories/_form.html.haml
= form_for [@site, @category] do |f|
  .py
    = f.label :title
    = f.text_field :title, class: "form-control"
  .py
    = f.label_with_hint :background_image
    = f.file_field :background_image, class: "form-control"
    = max_width_image_tag @category.background_image.url, 300

  .py
    = label_tag :pages, t('categories.shared.pages')
    = " - "
    %span.s= t('categories.shared.pages_hint')
    - @all_pages.each do |page|
      - if orphan_page?(page) || page_belong_to_category?(page, @category)
        .pyh
          = check_box_tag "page_ids[]", page.id, page_belong_to_category?(page, @category), id: page.id
          = label_tag page.id, page.title

  .pyh
    = f.submit t('shared.save'), class: "btn btn-block SPColorButton SPBlueColorButton"

app/views/categories/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    .container
      %h2= page_title t('categories.edit.title')
      = render "shared/errors", object: @category

      = render "categories/form"

app/views/categories/index.html.haml
.row
  .col-md-1 &nbsp;
  .col-md-10
    .container
      %h2= page_title t('categories.index.title')
      = t('categories.index.sub_title')

      %table.table.table-striped.mtd
        %thead
          %tr
            %th{width: "40%"}= t('categories.index.thead_title')
            %th{width: "35%"}= t('categories.index.thead_pages')
            %th &nbsp;
            %th &nbsp;
        %tbody
          - if @categories.any?
            - @categories.each do |category|
              %tr
                %td= category.title
                %td= pages_inside category
                %td= edit_link edit_site_category_path(@site, category)
                %td= delete_link site_category_path(@site, category)
          - else
            = render "shared/empty", colspan: 4

      .p
        = link_to t('categories.index.submit'), new_site_category_path(@site), class: "SPColorButton SPGreenColorButton"
  .col-md-1 &nbsp;

app/views/categories/new.html.haml
.row
  .col-md-6.col-md-offset-3
    .container
      %h1= t('categories.new.title')
      = render "shared/errors", object: @category

      = render "categories/form"